package com.iisi.example.model.test2;

// Generated 2012-3-8 9:48:37 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Company generated by hbm2java
 */
@Entity
@Table(name = "COMPANY", schema = "dbo", catalog = "test2")
public class Company implements java.io.Serializable {

	private String companyName;
	private String description;

	public Company() {
	}

	public Company(String companyName) {
		this.companyName = companyName;
	}

	public Company(String companyName, String description) {
		this.companyName = companyName;
		this.description = description;
	}

	@Id
	@Column(name = "CompanyName", unique = true, nullable = false, length = 20)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@Column(name = "description", length = 200)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
