package com.iisi.example.model.test1;

// Generated 2012-3-8 13:55:38 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "CUSTOMER", schema = "dbo", catalog = "test1")
public class Customer implements java.io.Serializable {

	private int customerId;
	private String customerName;
	private String company;

	public Customer() {
	}

	public Customer(int customerId, String customerName) {
		this.customerId = customerId;
		this.customerName = customerName;
	}

	public Customer(int customerId, String customerName, String company) {
		this.customerId = customerId;
		this.customerName = customerName;
		this.company = company;
	}

	@Id
	@Column(name = "CustomerId", unique = true, nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "CustomerName", nullable = false, length = 50)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "Company", length = 100)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

}
