package com.iisi.example.model.test1;

// Generated 2012-3-8 13:55:38 by Hibernate Tools 3.3.0.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "USERS", schema = "dbo", catalog = "test1")
public class Users implements java.io.Serializable {

	private String userName;
	private String password;

	public Users() {
	}

	public Users(String userName, String password) {
		this.userName = userName;
		this.password = password;
	}

	@Id
	@Column(name = "UserName", unique = true, nullable = false, length = 20)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "Password", nullable = false, length = 50)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
